services:
    php74:
        build:
            dockerfile: docker/Dockerfile
            args:
                PHP_VERSION: '7.4'
        ports:
            - '8074:8000'

    php80:
        build:
            dockerfile: docker/Dockerfile
            args:
                PHP_VERSION: '8.0'
        ports:
            - '8080:8000'

    php81:
        build:
            dockerfile: docker/Dockerfile
            args:
                PHP_VERSION: '8.1'
        ports:
            - '8081:8000'

    php82:
        build:
            dockerfile: docker/Dockerfile
            args:
                PHP_VERSION: '8.2'
        ports:
            - '8082:8000'

    php83:
        build:
            dockerfile: docker/Dockerfile
            args:
                PHP_VERSION: '8.3'
        ports:
            - '8083:8000'

    php84:
        build:
            dockerfile: docker/Dockerfile
            args:
                PHP_VERSION: '8.4'
        ports:
            - '8084:8000'

    mysql:
        image: docker.io/mysql:8.0
        ports:
            - "33066:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=pwd
            - MYSQL_DATABASE=testrabbit
        volumes:
            - mysql-data:/var/lib/mysql

    memcache:
        image: docker.io/memcached:1.6-alpine
        ports:
            - "11211:11211"
        command: memcached -m 64 -I 1m

volumes:
    mysql-data:
