services:
    php74:
        build:
            dockerfile: docker/Dockerfile
            args:
                PHP_VERSION: '7.4'
        image: ghcr.io/fortrabbit/testrabbit:7.4
        ports:
            - '8074:8000'
        volumes:
            - './:/var/www/html'

    php80:
        build:
            dockerfile: docker/Dockerfile
            args:
                PHP_VERSION: '8.0'
        image: ghcr.io/fortrabbit/testrabbit:8.0
        ports:
            - '8080:8000'
        volumes:
            - './:/var/www/html'

    php81:
        build:
            dockerfile: docker/Dockerfile
            args:
                PHP_VERSION: '8.1'
        image: ghcr.io/fortrabbit/testrabbit:8.1
        ports:
            - '8081:8000'
        volumes:
            - './:/var/www/html'

    php82:
        build:
            dockerfile: docker/Dockerfile
            args:
                PHP_VERSION: '8.2'
        image: ghcr.io/fortrabbit/testrabbit:8.2
        ports:
            - '8082:8000'
        volumes:
            - './:/var/www/html'

    mysql:
        image: docker.io/mysql:8.0
        ports:
            - "33066:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=pwd
            - MYSQL_DATABASE=testrabbit
        volumes:
            - mysql-data:/var/lib/mysql

    memcache:
        image: docker.io/memcached:1.6-alpine
        ports:
            - "11211:11211"
        command: memcached -m 64 -I 1m

volumes:
    mysql-data:
