name: Test & Deploy
env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PubkeyAcceptedKeyTypes=+ssh-rsa"
  DOCKER_REGISTRY_IMAGE: ghcr.io/fortrabbit/testrabbit

on:
  push:
    branches:
      - master
      - develop
      - production
    tags:
      - '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]-?*'

jobs:

  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php-version: ['7.4','8.0','8.1','8.2']

    steps:
      - uses: actions/checkout@v3

      -   name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image using Github Packages as cache
        env:
          PHP_VERSION: ${{ matrix.php-version }}
        run: |
          docker pull $DOCKER_REGISTRY_IMAGE:${PHP_VERSION} || true
          cd docker/$PHP_VERSION
          docker build --build-arg PHP_VERSION=${PHP_VERSION} \
            --cache-from $DOCKER_REGISTRY_IMAGE:${PHP_VERSION} \
            --tag $DOCKER_REGISTRY_IMAGE:${PHP_VERSION} \
            --tag $DOCKER_REGISTRY_IMAGE:latest .
          docker push $DOCKER_REGISTRY_IMAGE:${PHP_VERSION}

      - name: Cache vendor folder
        uses: actions/cache@v3
        with:
          path: vendor
          key: vendor-${{ matrix.php-version }}-${{ hashFiles('composer.lock') }}

      - name: Install dependencies
        run: |
          docker run --rm \
            -v $PWD:/var/www/html \
            $DOCKER_REGISTRY_IMAGE:${{ matrix.php-version }} \
            bash -c '\
            composer config -g github-oauth.github.com ${{ secrets.ACTIONS_TOKEN }} && \
            composer install --no-interaction --prefer-dist --no-scripts --no-cache'


  usx:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      -   name: Checkout
          uses: actions/checkout@v3
          with:
            # fetch all history so we can push to remotes
            fetch-depth: 0

      -   name: Setup SSH Keys and known_hosts
          run: |
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<EOF
            ${{ secrets.SSH_PRIVATE_KEY }}
            EOF
            ssh-add -l

      -   name: 'Run deployment to testrabbit-pro'
          run: |
            git push --force testrabbit-pro@deploy.usx.frbit.com:testrabbit-pro.git HEAD:master

      -   name: 'Run deployment to testrabbit-uni'
          run: |
            git push --force testrabbit-uni@deploy.usx.frbit.com:testrabbit-uni.git HEAD:master

  eu2:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      -   name: Checkout
          uses: actions/checkout@v3
          with:
            # fetch all history so we can push to remotes
            fetch-depth: 0

      -   name: Setup SSH Keys and known_hosts
          run: |
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<EOF
            ${{ secrets.SSH_PRIVATE_KEY }}
            EOF
            ssh-add -l

      -   name: 'Run deployment to testrabbit-pro'
          run: |
            git push --force testrabbit-pro@deploy.eu2.frbit.com:testrabbit-pro.git HEAD:master
            #echo "slack_environment=EU2" >> $GITHUB_ENV

      -   name: 'Run deployment to testrabbit-uni'
          run: |
            git push --force testrabbit-uni@deploy.eu2.frbit.com:testrabbit-uni.git HEAD:master

  us1:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      -   name: Checkout
          uses: actions/checkout@v3
          with:
            # fetch all history so we can push to remotes
            fetch-depth: 0

      -   name: Setup SSH Keys and known_hosts
          run: |
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<EOF
            ${{ secrets.SSH_PRIVATE_KEY }}
            EOF
            ssh-add -l

      -   name: 'Run deployment to testrabbit-us1'
          run: |
            git push --force testrabbit-us1@deploy.us1.frbit.com:testrabbit-us1.git HEAD:master

      -   name: 'Run deployment to testrabbit-us1-u'
          run: |
            git push --force testrabbit-us1-u@deploy.us1.frbit.com:testrabbit-us1-u.git HEAD:master
